# image will be published to ghcr.io/<user>/<name>
name: ublue-secure
# description will be included in the image's metadata
description: "This is my personal OS image - add some secure config from ublue secure but kept firefox."

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: script
    scripts:
      - createautostartdir.sh
      - disablecups.sh
      - removecinnamonxsessions.sh
      # - disableuserns.sh
      # - flathubsetup.sh

  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    install:
      - gnome-console
      - usbguard
      - usbguard-dbus
      - usbguard-notifier
      - firewall-config
      - gnome-disk-utility
      - setools
      - setroubleshoot
      - vim
      - logiops
    remove:
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - gnome-terminal
      - gnome-terminal-nautilus
      - gnome-tour
      - yelp
      - gnome-user-share
      - mod_lua
      - httpd
      - httpd-core
      - mod_http2
      - mod_dnssd
      - gnome-remote-desktop
      - libvncserver
      - malcontent-ui-libs
      - malcontent-control
      - openssh-server
      - fedora-flathub-remote
      - open-vm-tools
      - open-vm-tools-desktop
      - virtualbox-guest-additions
      # - podman
      - toolbox
      # - docker

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.mozilla.firefox
        - org.mozilla.Thunderbird
        - org.libreoffice.LibreOffice
        - com.github.tchx84.Flatseal
        - org.gnome.Calculator
        - org.gnome.baobab
        - org.gnome.Loupe
        - org.gnome.TextEditor
        # - com.yubico.yubioath
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

